{
 "title": "Historical graphical data",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "New infected vs. test performed by day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \n\tdata as time, \n\tsum(nuovi_attualmente_positivi) as \"new infected\", \n\tsum(tamponi) - \t\n\t\t\t(\n\t\t\t\tselect \n\t\t\t\t\tsum(tamponi) \n\t\t\t\tfrom \n\t\t\t\t\t\"dati-regioni\" b\n\t\t\t\twhere \n\t\t\t\t\tdate(data) = date(a.data - INTERVAL '1 DAY') \n\t\t\t\tgroup by \n\t\t\t\t\tdata \n\t\t\t)\n\t as \"test performed\" \n\tfrom \n\t\t\"dati-regioni\" a\n\tgroup by \n\t\tdata \n\torder by \n\t\tdata"
    }
   ]
  },
  {
   "title": "Italy's infections trend by day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select data as time, sum(totale_casi-dimessi_guariti-deceduti) as current, sum(totale_casi) as total, sum(dimessi_guariti) as healed, sum(deceduti) as deceased from public.\"dati-regioni\" group by data order by data desc"
    }
   ]
  },
  {
   "title": "New infected in Italy by day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select data as time, sum(nuovi_attualmente_positivi) from public.\"dati-regioni\" group by data order by data"
    }
   ]
  },
  {
   "title": "Infection speed by day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \n\tdata as time, \n\t100 * sum(nuovi_attualmente_positivi) /\n\t(\n\t\t  \n\t\tsum(tamponi) - \t\n\t\t\t(\n\t\t\t\tselect \n\t\t\t\t\tsum(tamponi) \n\t\t\t\tfrom \n\t\t\t\t\t\"dati-regioni\" b\n\t\t\t\twhere \n\t\t\t\t\tdate(data) = date(a.data - INTERVAL '1 DAY') \n\t\t\t\tgroup by \n\t\t\t\t\tdata \n\t\t\t)\n\t ) \n\t as \"infection speed %\" \n\tfrom \n\t\t\"dati-regioni\" a\n\tgroup by \n\t\tdata \n\torder by \n\t\tdata"
    }
   ]
  },
  {
   "title": "Deceased",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \n\tdata as time, \n\tsum(deceduti) as \"total\",\n\tsum(deceduti) - \t\n\t\t\t(\n\t\t\t\tselect \n\t\t\t\t\tsum(deceduti) \n\t\t\t\tfrom \n\t\t\t\t\t\"dati-regioni\" b\n\t\t\t\twhere \n\t\t\t\t\tdate(data) = date(a.data - INTERVAL '1 DAY') \n\t\t\t\tgroup by \n\t\t\t\t\tdata \n\t\t\t)\n\t as \"today\" \n\tfrom \n\t\t\"dati-regioni\" a\n\tgroup by \n\t\tdata\n\torder by \n\t\tdata"
    }
   ]
  }
 ]
}