{
 "title": "Current number data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LAST_DATA_DATE",
    "query": "select distinct data from public.\"dati-regioni\" order by data desc limit 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Healed (last update $LAST_DATA_DATE)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select data as time, sum(dimessi_guariti) as \"Healed\" from \"dati-regioni\" where date(data) = date('$LAST_DATA_DATE') group by data"
    }
   ]
  },
  {
   "title": "Total infected (last update $LAST_DATA_DATE)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select data as time, sum(totale_casi) as \"Total infected\" from \"dati-regioni\" where date(data) = date('$LAST_DATA_DATE') group by data"
    }
   ]
  },
  {
   "title": "Deceased (last update $LAST_DATA_DATE)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select data as time, sum(deceduti) as \"Deceased\" from \"dati-regioni\" where date(data) = date('$LAST_DATA_DATE') group by data"
    }
   ]
  },
  {
   "title": "Currently infected (last update $LAST_DATA_DATE)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select data as time, sum(totale_attualmente_positivi) as \"Currently infected\" from \"dati-regioni\" where date(data) = date('$LAST_DATA_DATE') group by data"
    }
   ]
  }
 ]
}