{
 "title": "COVID-19 Italy status",
 "time": { "from": "now-15d/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LAST_DATA_DATE",
    "query": "select distinct data from public.\"dati-regioni\" order by data desc limit 1"
   }
  ]
 },
 "panels": [
  {
   "title": "New infected in Italy by day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select data as time, sum(nuovi_attualmente_positivi) from public.\"dati-regioni\" group by data order by data"
    }
   ]
  },
  {
   "title": "Total infected (last update $LAST_DATA_DATE)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select data as time, sum(totale_casi) as \"Total infected\" from \"dati-regioni\" where date(data) = date('$LAST_DATA_DATE') group by data"
    }
   ]
  },
  {
   "title": "Currently infected (last update $LAST_DATA_DATE)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select data as time, sum(totale_attualmente_positivi) as \"Currently infected\" from \"dati-regioni\" where date(data) = date('$LAST_DATA_DATE') group by data"
    }
   ]
  },
  {
   "title": "Healed (last update $LAST_DATA_DATE)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select data as time, sum(dimessi_guariti) as \"Healed\" from \"dati-regioni\" where date(data) = date('$LAST_DATA_DATE') group by data"
    }
   ]
  },
  {
   "title": "Deceased (last update $LAST_DATA_DATE)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select data as time, sum(deceduti) as \"Deceased\" from \"dati-regioni\" where date(data) = date('$LAST_DATA_DATE') group by data"
    }
   ]
  },
  {
   "title": "Italy's infections trend by day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select data as time, sum(totale_casi-dimessi_guariti-deceduti) as current, sum(dimessi_guariti) as healed, sum(deceduti) as deceased from public.\"dati-regioni\" group by data order by data desc"
    }
   ]
  },
  {
   "title": "Currently infected in Italy (last update $LAST_DATA_DATE)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 27, "w": 12, "x": 12, "y": 12 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select data as time, lat, long, denominazione_regione, totale_attualmente_positivi as total from public.\"dati-regioni\" where date(data) = date('$LAST_DATA_DATE')"
    }
   ]
  },
  {
   "title": "Currently infected by region (last update $LAST_DATA_DATE)",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select data as time, totale_attualmente_positivi as total, denominazione_regione from public.\"dati-regioni\" where date(data) = date('$LAST_DATA_DATE') order by totale_attualmente_positivi\n"
    }
   ]
  }
 ]
}